CONFIG_TFM_PROFILE_TYPE_MINIMAL=y

CONFIG_NETWORKING=y
CONFIG_NRF_MODEM_LIB=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_OFFLOAD=y
CONFIG_POSIX_API=y
# NET_NATIVE needs to be n to turn off the software implementation
# in zephyr and instead use what the hardware has. The nameing is
# "slightly" misleading.
CONFIG_NET_NATIVE=n

# documentation for nrf modem lib recommends this
CONFIG_HEAP_MEM_POOL_SIZE=4096
CONFIG_MAIN_STACK_SIZE=8192

CONFIG_MODEM_KEY_MGMT=y
CONFIG_LTE_LINK_CONTROL=y

# Own modifications

CONFIG_MODEM_INFO=y
CONFIG_NRF_MODEM_LIB_ON_FAULT_RESET_MODEM=y
CONFIG_NRF_MODEM_LIB_FAULT_STRERROR=y
CONFIG_GPIO=y
CONFIG_NRFX_GPIOTE_NUM_OF_EVT_HANDLERS=1
CONFIG_POSIX_UNAME_NODENAME_LEN=6
CONFIG_NET_HOSTNAME="foxmobtemp"
CONFIG_NET_HOSTNAME_UNIQUE=y
CONFIG_I2C=y
CONFIG_I2C_NRFX=y
# Recommended for powersaving
CONFIG_LTE_PSM_REQ=y
CONFIG_LTE_EDRX_REQ=y
CONFIG_LTE_LC_EDRX_MODULE=y
# Enable GNSS - and LTE-M and NBIOT.
CONFIG_LTE_NETWORK_MODE_LTE_M_NBIOT_GPS=y
# Enable the location part of the library
CONFIG_LOCATION=y
CONFIG_LOCATION_METHOD_GNSS=y
CONFIG_LOCATION_METHOD_CELLULAR=n
# The mini library for the onboard buttons and LEDs
CONFIG_DK_LIBRARY=y
# we want to handle / print floating point numbers.
CONFIG_FPU=y
CONFIG_PICOLIBC_IO_FLOAT=y


